### PR TITLE
Fix owner removal for duplicate logins

### LINKED ISSUE #2736: Can't remove invalid users from crate owners
This is similar to #1818 but for users.

## What happened

- A user had a GitHub account named, let's say, `foo`.
- Another user `someone_else` added them as an owner of a crate
- `foo` deleted their GitHub account (but crates.io has no real knowledge of this)
- `foo` recreated their GitHub account with the same username (because it was still available), but in this situation GitHub assigns them a new ID
- When `foo` now logs in to crates.io, it's a different account than their old `foo` crates.io account because of the new GitHub ID (and if it wasn't, this would be a security problem)
- The new `foo` account is NOT an owner of the crate
- `someone_else` can't add the new `foo` account as an owner, nor can they remove the old `foo` as an owner :(

## What should happen

- Removing an owner, whether it's valid/current or not, should always work (if performed by another valid owner, etc)
- Once that removal works, it should be possible to add the new account as an owner

### PR DESCRIPTION
**Pull request by Turbo87**
When users or teams on GitHub are deleted and recreated they might exist multiple times within our own database with the same `login`. When owners are deleted, only the newest matching `login` is considered for deletion though, which makes it impossible to delete older users/teams.

This commit fixes the problem by deleting **all** owners with a matching `login` instead.

Unfortunately, `diesel` does not support `UPDATE` queries with `JOINs`, so this has to be a "raw" SQL query with bindings instead…

Fixes #2736, ~~and AFAICT also fixes https://github.com/rust-lang/crates.io/issues/1205~~

Related:

- https://github.com/rust-lang/crates.io/issues/1205
- #2736
- https://github.com/rust-lang/crates.io/issues/1818
- https://github.com/rust-lang/crates.io/issues/1512
- https://github.com/rust-lang/crates.io/pull/7051

### CODE REVIEW

**Comment by carols10cents** [comment]
Wait, what about this case:

- User `foo`, github ID 1 that is Person A has logged in to crates.io 
- Person A renames their github account to `bar` but does NOT log in to crates.io
- Person B creates a new github account named `foo` with github ID 2 and logs in to crates.io
- Person A logs in to crates.io with their account that's now named `bar` but still has github ID 1, I believe the current behavior is crates.io updates the gh_login and everything Just Works because the gh_id matches

I think what you're saying is this PR would delete the record for Person A when Person B logs in??? So when Person A logs in again, their account/ownership stuff would be gone?

**Comment by carols10cents** [comment]
OH WAIT I think I'm confused. I read this line:

> which makes it impossible to delete older users/teams.

and thought the records in the `users` table were being deleteed, but you're talking about the `crate_owners` table. Carry on, I think.

**Comment by Turbo87** [comment]
> and thought the records in the `users` table were being deleted, but you're talking about the `crate_owners` table

yep, exactly :)

File: src/models/krate.rs [hunk 1]
```diff
@@ -453,12 +453,43 @@ impl Crate {
...
-            .set(crate_owners::deleted.eq(true))
+        let num_updated_rows = query
+            .bind::<Integer, _>(self.id)
+            .bind::<Text, _>(login)
             .execute(conn)?;
+
+        if num_updated_rows == 0 {
+            let error = format!("could not find owner with login `{login}`");
+            return Err(bad_request(error));
+        }
```
Comment (eth3lbert) [inline src/models/krate.rs:491]: Should we add a `NOT deleted` condition here? However, it might be a bad idea to work with the `num_updated_rows == 0` check below.

File: src/tests/routes/crates/owners/remove.rs [hunk 2]
```diff
@@ -78,5 +81,73 @@ async fn test_unknown_team() {
...
+
+    assert_eq!(github_ids.len(), 2);
+    assert_ne!(github_ids[0], github_ids[1]);
+
+    // - The new `foo` account is NOT an owner of the crate
+    let owner_ids = crate_owners::table
+        .filter(crate_owners::crate_id.eq(krate.id))
+        .filter(crate_owners::deleted.eq(false))
+        .select(crate_owners::owner_id)
+        .load::<i32>(&mut conn)?;
```
Comment (eth3lbert) [inline src/tests/routes/crates/owners/remove.rs:131]: Not a blocker, but should we replace this with something like
```suggestion
    let owner_ids = CrateOwner::by_owner_kind(OwnerKind::User)
        .filter(crate_owners::crate_id.eq(krate.id))
        .select(crate_owners::owner_id)
        .load::<i32>(&mut conn)?;
         // or something that map from
         // krate.owners(&mut conn)?
```
 as we usually use these?

**Review by eth3lbert — COMMENTED** [review]
LGTM on first glance :)

File: src/models/krate.rs (hunk 1 above)
Comment (Turbo87) [reply src/models/krate.rs:491]: > Should we add a `NOT deleted` condition here?

hmm, yeah, that seems like a good idea.

**Comment by Turbo87** [comment]
> should we add some tests for the team-related parts?

I've added https://github.com/rust-lang/crates.io/pull/9943 just now, but it looks like there is no fix needed for that issue since it already works as intended.

**Comment by eth3lbert** [comment]
> Wait, what about this case:
> 
>     * User `foo`, github ID 1 that is Person A has logged in to crates.io
> 
>     * Person A renames their github account to `bar` but does NOT log in to crates.io
> 
>     * Person B creates a new github account named `foo` with github ID 2 and logs in to crates.io
> 
>     * Person A logs in to crates.io with their account that's now named `bar` but still has github ID 1, I believe the current behavior is crates.io updates the gh_login and everything Just Works because the gh_id matches
> 
> 
> I think what you're saying is this PR would delete the record for Person A when Person B logs in??? So when Person A logs in again, their account/ownership stuff would be gone?

If I understand correctly, in this case, Person B is not the owner of the crate, and they also do not have permission to change the owner. So, there should not be an issue here.

File: src/tests/issues/issue2736.rs [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+    let owners = krate.owners(&mut conn)?;
+    assert_eq!(owners.len(), 2);
+    assert_none!(owners.iter().find(|o| o.id() == foo2.as_model().id));
+
+    // - `someone_else` can't add the new `foo` account as an owner, nor can they remove the old `foo` as an owner :(
+    let url = "/api/v1/crates/crate1/owners";
+    let payload = json!({ "owners": ["foo"] }).to_string();
+    let response = someone_else.delete_with_body::<()>(url, payload).await;
+    assert_eq!(response.status(), StatusCode::OK);
+    assert_snapshot!(response.text(), @r#"{"msg":"owners successfully removed","ok":true}"#);
```
Comment (eth3lbert) [inline src/tests/issues/issue2736.rs:56]: The comment said, "Nor can they remove the old foo as an owner :("

but the response was `OK` ;)

Comment (Turbo87) [reply src/tests/issues/issue2736.rs]: fixed

**Review by eth3lbert — APPROVED** [review]
The regression test confirms that the issue has been fixed as expected. The SQL part leverages `bind`, which should prevent any injection attacks.
Nice work, thanks 👍
