### PR TITLE
Drop Email column (merge and deploy the fix for #1888 first!)

### LINKED ISSUE #1889: Cleanup: drop the `email` column on the `users` table
Can only be done after https://github.com/rust-lang/crates.io/issues/1888 is fixed. That issue is to remove all uses of `email` field on `User` from the Rust code.

What needs to be done:

- Generate a migration using the diesel CLI (search [this guide](https://diesel.rs/guides/getting-started/) for "diesel migration generate" for more instructions)
- In `up.sql`, drop the `email` column from the `users` table.
- In `down.sql`, leave a comment that this migration isn't really reversible since we're deleting data [like this migration has](https://github.com/rust-lang/crates.io/blob/master/migrations/20170728002039_fix_keywords/down.sql), but also restore the column with nulls.
- Run the migration and commit the schema changes along with the new migration.

### PR DESCRIPTION
**Pull request by hogum**
#### Fixes #1889

This cleans up the uses of the field `email` from `User` by:
- dropping the `email` field from `User`
- clearing references to the dropped email field
- migrating and updating the schema changes

### CODE REVIEW

**Comment by hogum** [comment]
How should the `database visibility configuration` be updated after modifying the schema?
Its test fails with:
```
---- tasks::dump_db::gen_scripts::tests::check_visibility_config stdout ----
thread 'tasks::dump_db::gen_scripts::tests::check_visibility_config' panicked at 'The visibility configuration does not match the database schema:
Column users.email does not exist in the database.', src/tasks/dump_db/gen_scripts.rs:204:9
```

**Comment by carols10cents** [comment]
> How should the `test database visibility configuration` be updated after modifying the schema?
> It fails with:
> 
> ```
> ---- tasks::dump_db::gen_scripts::tests::check_visibility_config stdout ----
> thread 'tasks::dump_db::gen_scripts::tests::check_visibility_config' panicked at 'The visibility configuration does not match the database schema:
> Column users.email does not exist in the database.', src/tasks/dump_db/gen_scripts.rs:204:9
> ```

Removing [the users.email line from the dump-db.toml file](https://github.com/rust-lang/crates.io/blob/23f187ac703cd2e4e36621729f550f4c6f8be9de/src/tasks/dump_db/dump-db.toml#L168) should do it. The dump-db.toml file is configuration for the public database dumps we make, and this test ensures the database schema is always in sync with this configuration so that we don't accidentally leak data. 

I'll make the error message for that test a bit clearer to point at what needs to be done.

**Comment by hogum** [comment]
Thanks @carols10cents! That sorted it out.
Dumping to the emails table originally required the `user: email` column - what would be the reason for getting a unique key violation on `emails: user_id` after dropping the `users: email` column. 

https://github.com/rust-lang/crates.io/blob/23f187ac703cd2e4e36621729f550f4c6f8be9de/migrations/20170804200817_add_email_table/up.sql#L16-L17

**Comment by carols10cents** [comment]
> Dumping to the emails table originally required the `user: email` column - what would be the reason for getting a unique key violation on `emails: user_id` after dropping the `users: email` column.

I'm confused, are you getting a unique key violation? Can you give me steps to reproduce?

**Comment by carols10cents** [comment]
Oh I see the errors in travis now. Investigating!

File: migrations/2019-11-11-162609_drop_email_from_user/up.sql [hunk 1]
```diff
@@ -0,0 +1,2 @@
+-- Your SQL goes here
```
Comment (carols10cents) [inline migrations/2019-11-11-162609_drop_email_from_user/up.sql]: You can remove this comment :)

File: migrations/2019-11-11-162609_drop_email_from_user/up.sql [hunk 2]
```diff
@@ -0,0 +1,2 @@
...
+ALTER TABLE  users DROP COLUMN email CASCADE;
```
Comment (carols10cents) [inline migrations/2019-11-11-162609_drop_email_from_user/up.sql]: This is super picky, but can you remove the extra space between `TABLE` and `users`?

File: src/controllers/user/me.rs [hunk 3]
```diff
@@ -38,10 +38,10 @@ pub fn me(req: &mut dyn Request) -> CargoResult<Response> {
 
     let verified = verified.unwrap_or(false);
     let verification_sent = verified || verification_sent;
-    let user = User { email, ..user };
+    let user = User { ..user };
```
Comment (carols10cents) [inline src/controllers/user/me.rs]: I think this line can be completely removed now, actually! I think `user = User { ..user }` is doing a no-op.

File: src/models/user.rs [hunk 4]
```diff
@@ -179,19 +185,21 @@ impl User {
     /// Converts this `User` model into an `EncodablePrivateUser` for JSON serialization.
     pub fn encodable_private(
         self,
+        email: Option<String>,
+
         email_verified: bool,
         email_verification_sent: bool,
-    ) -> EncodablePrivateUser {
+    ) -> CargoResult<EncodablePrivateUser> {
```
Comment (carols10cents) [inline src/models/user.rs]: Can you explain why this function needed to be changed to return a `Result`? It doesn't look like it's necessary to me because I don't see anywhere returning an `Err` variant. Am I missing something?

File: src/models/user.rs [hunk 5]
```diff
@@ -13,20 +13,19 @@ use crate::views::{EncodablePrivateUser, EncodablePublicUser};
...
     pub id: i32,
-    pub email: Option<String>,
     pub gh_access_token: String,
     pub gh_login: String,
     pub name: Option<String>,
     pub gh_avatar: Option<String>,
     pub gh_id: i32,
 }
 
+/// Represents a new user record insertible to the `users` table
```
Comment (carols10cents) [inline src/models/user.rs]: Small fix: can you change `insertible` to `insertable` in this comment please?

File: src/tests/util.rs [hunk 6]
```diff
@@ -135,9 +135,10 @@ impl TestApp {
         use diesel::prelude::*;
 
         let user = self.db(|conn| {
-            let mut user = crate::new_user(username).create_or_update(conn).unwrap();
-            let email = "something@example.com";
-            user.email = Some(email.to_string());
+            let email = "cow@mammals.milk";
+            let user = crate::new_user(username)
+                .create_or_update(Some(email), conn)
```
Comment (carols10cents) [inline src/tests/util.rs]: Aha, so the unique constraint that's causing the tests to fail is that here in the test setup you're creating a new user with an email set, then [lines 142-149 right after this](https://github.com/rust-lang/crates.io/pull/1891/files#diff-2bda8a5d16907d0b0ef38311d9dccb43R142-R149) the test setup is inserting the email into the table directly, which violates [the constraint we have that each user may only have one email](https://github.com/rust-lang/crates.io/blob/21e04f3028624485621d577359008560728a37d3/migrations/20170804200817_add_email_table/up.sql#L7).

To fix this, you can pass `None` to `create_or_update` here and the next part will take care of inserting the email (and setting it to verified, which is important for the tests).

File: src/models/user.rs (hunk 4 above)
Comment (hogum) [reply src/models/user.rs]: It isn't necessary. I was previously reading this `email` variable from the database with an `Err`

https://github.com/rust-lang/crates.io/blob/3544b91086e822607cfeadda57b261e66112ba52/src/models/user.rs#L86

variant result before realizing [that was already "done"](https://github.com/rust-lang/crates.io/blob/3544b91086e822607cfeadda57b261e66112ba52/src/controllers/user/me.rs#L28-L37) and the email could simply be passed to the `src/models/users/encodable_private` function as an argument.
I definitely forgot to undo that modification to the return type - will do so now

File: migrations/2019-11-11-162609_drop_email_from_user/up.sql (hunk 2 above)
Comment (hogum) [reply migrations/2019-11-11-162609_drop_email_from_user/up.sql]: :)

File: src/tests/user.rs [hunk 7]
```diff
@@ -510,12 +514,13 @@ fn test_confirm_user_email() {
 
     // Simulate logging in via GitHub. Don't use app.db_new_user because it inserts a verified
     // email directly into the database and we want to test the verification flow here.
+    let email = "cow@mammals@milk";
```
Comment (carols10cents) [inline src/tests/user.rs]: I'm curious, why is the value different here? Any particular reason, and any reason why it's not a valid email address (two `@`s)?

**Comment by hogum** [comment]
Resolved. The invalid email address was a mistake I hadn't noted. Is it not supposed to be caught? I'm surprised it passes the test

**Comment by hogum** [comment]
Resolved. The invalid email address was a mistake I hadn't noted. Is it not supposed to be caught? I'm surprised it passes the test

**Comment by carols10cents** [comment]
Thank you so much!! This looks great, but I'm not going to merge it yet-- we need to merge and deploy https://github.com/rust-lang/crates.io/issues/1888 to remove all the *uses* of the email column first, so that there aren't any connections using the `email` field when we deploy this PR.

**Comment by carols10cents** [comment]
I removed some more of the temporary code that was needed to deploy the code that stopped using the email column (and that has been deployed). I also introduced more merge conflicts by merging another PR just now; I'll be fixing those in a few hours.

**Comment by carols10cents** [comment]
I think this is ready to go now!! Thank you!!!

@bors r+
